### ISSUE TITLE
Edge extraction

### ISSUE THREAD

**Issue by nifla2000** [MungoMeng/Image-Registration-AAN#2]
Hi Mingyuan,

Thanks for the interesting work.

I have a question regarding the edge extraction pipeline. I'm performing experiments on IXI dataset. Can you specify how to perform edge extraction as per your code ?

**Comment by MungoMeng** [comment]
Thanks for your interest in our work!

You can use the CannyEdgeDetectionImageFilter function in the SimpleITK package.
The low and high thresholds are hyperparameters that should be adjusted for different datasets.

Don't worry too much about the detailed settings -- the edge detection accuracy is not very important and a very coarse edge map also can work well.

**Comment by nifla2000** [comment]
Thanks for your information,
To start with the implementations, can you provide me an example of a preprocessed public dataset? Or it would be great if you could give a quick note to generate .npz files with all 'vol', 'label', and 'edge' np_var. Thanks

**Comment by MungoMeng** [comment]
I am sorry the preproceesed dataset is currently unavailable as this study was performed two years ago.

For the .npz files, you can simply save the image (vol), edge map (edge), and segmentation mask (label) of the same patient into a single npz file. Or you can define your own data generation code based on your current data structure and then embed our core code in network.py into your own code framework.

**Comment by nifla2000** [comment]
Thank you!
