### ISSUE TITLE
#Dimension mismatch and unable to concatenate

### ISSUE THREAD

**Issue by nifla2000** [MungoMeng/Image-Registration-AAN#3]
Hi,
When trying to encode and decode images with odd shapes (at least one dimension)the concatenation of encoder-decoder output results in dimension mismatch as many Unet-based models do. Did you reshape your inputs as multiples of 64? I got this error with the IXI dataset which has dimensions of (256,256,150). 
Please let me know if anyone is aware of this issue.

**Comment by MungoMeng** [comment]
Hi, as you said, this is a common issue in the Unet-based network.
To address it, you can crop the input image or pad the feature maps during upsampling.

This code did not consider this issue as our input images have been preprocessed to the size of (192, 160, 144). 
Please refer to the paper for detailed image preprocessing.
