### ISSUE TITLE
#Segmentation

### ISSUE THREAD

**Issue by nifla2000** [MungoMeng/Image-Registration-AAN#4]
Meng, Thank you for your previous responses.
When testing the segmentation is a must ('label'). Can you please clarify how you created or preprocessed your test dataset? Because in the dataset I downloaded (LPBA40 I can only see segmentation masks)
Thank you

**Comment by MungoMeng** [comment]
Hi Nifla,

In the test.py, the --label indicates a npy file that contains a list [label_tag_1, label_tag_2, label_tag_3, label_tag_4, ...].
The label_tag indicates the anatomical structures involved into the calcuation of Dice.

If you want to calculate the Dice based on all the available anatomical structures in the segmentation masks, you can simply set the 'label' as None. Please refer to the Dice function in medipy package:
https://github.com/MungoMeng/Registration-AAN/blob/343f85abe313975af62cb10248009edcb39ff62a/AAN/ext/medipy/metrics.py#L11

**Comment by nifla2000** [comment]
Thank you Meng!

**Comment by nifla2000** [comment]
But to run the test file I should have a segmentation mask because it is needed in test.py

**Comment by MungoMeng** [comment]
The segmetation masks have been provided along with the dataset, such as LPBA40.
