### ISSUE TITLE
fixing_vol and fixing_seg

### ISSUE THREAD

**Issue by nifla2000** [MungoMeng/Image-Registration-AAN#5]
in test.py in line 102 you are using fixing_vol as an argument for net, predict which is not defined. Are you actually referring to fixed_vol? (also in line 118)

**Comment by MungoMeng** [comment]
Thank you for pointing out this error!
Yes, the fixing_vol and fixing_seg should be fixed_vol and fixed_seg.

**Comment by nifla2000** [comment]
Hi Ming,
I hope you are doing great. I have tried your AAN for a long time now. I
could not achieve good accuracy. I kindly request you to share your
pre-trained weights if you have any. Please consider sharing if possible.
Thank you in advance.
Regards,
Nifla

**Comment by MungoMeng** [comment]
Hi Nifla,
Thanks again for your interest in our work.
I am sorry I failed to find the pre-trained weights as this is a very old project.

Have you identified the improved performance when using AAN? For example, AAN+VM should outperform VM with the same architecture setting. But to be honest, if you aim for high accuracy, AAN is not the best choice.

Perhaps you can have a look at our latest works: 
https://github.com/MungoMeng/Registration-NICE-Trans/
This method can outperform VM and VM+AAN by a large margin.
